
name: Check if enough lines were changed to generate preview html files

on:
  pull_request:
    branches:
      - main
    paths:
      - src/G*/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if enough lines were changed
        id: enough_lines
        run: |
          git checkout ${{ github.head_ref }}

          LATEST=$(git rev-parse HEAD)
          SECOND_LATEST=$(git rev-parse HEAD~1)

          LINES_CHANGED=$(git diff --shortstat $SECOND_LATEST $LATEST | awk '{print $4 + $6}')

          echo "Lines changed: $LINES_CHANGED"

          if [ "$LINES_CHANGED" -gt 10 ]; then
            echo "continue=true" >> $GITHUB_ENV
          else
            echo "continue=false" >> $GITHUB_ENV
          fi

      - name: Dispatch other workflow if enough was changed
        if: env.continue == 'false'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: serve-preview
