name: Pre-deploy
on:
    push:
        paths:
            - src/**/*

jobs:
  check-changes:
    name: Check if Rmd files changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find changed rmd or image files
        id: changed-rmd
        uses: tj-actions/changed-files@v41
        with:
            files:  |
                src/G*/*.{rmd,Rmd}
                src/G*/img/*.{png,gif}
                src/G*/img/*/*.{png,gif}  

      - name: Deploy if files changed
        if: steps.changed-rmd.outputs.any_changed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: render-deploy