
name: Generate and serve changed course html files

on:
  pull_request:
    branches:
      - main
    paths:
      - src/G*/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check if enough lines were changed
        id: enough_lines
        run: |
          LATEST=$(git rev-parse HEAD)
          SECOND_LATEST=$(git rev-parse HEAD~1)

          LINES_CHANGED=$(git diff --shortstat $SECOND $LATEST | awk '{print $4 + $6}')

          echo "Lines changed: $LINES_CHANGED"

          echo "::set-output name=continue::true"
          exit 0

      - name: Continue if changes were big enough
        if: steps.enough_lines.outputs.continue == 'true'
        id: continue
        run: |
          echo "Continuing"
